// Questions authored in advance. Answers are constrained by the French instruction.
// Tuple: stable id, format, grammar reference, instruction, prompt, answer,
// distractors (or tiles for ordering), translation, explanation.
export const TYPES = {
  particle: 'Particules', vocabulary: 'Vocabulaire en contexte', conjugation: 'Conjugaison',
  order: 'Remettre en ordre', grammar: 'Structures grammaticales', dialogue: 'Dialogues',
  reading: 'Compréhension écrite', correction: 'Corriger une erreur', transform: 'Transformer une phrase',
};
const rows = [
 ['p01','particle','g017','Complète la particule.','ろくじ＿おきます。','に',['で','を','と'],'Je me lève à six heures.','に marque ici une heure précise.'],
 ['p02','particle','g023','Complète pour dire « Je bois de l’eau ».','みず＿のみます。','を',['に','で','と'],'Je bois de l’eau.','を marque ce que l’on boit, le complément du verbe.'],
 ['p03','particle','g024','Indique le lieu où l’on étudie.','としょかん＿べんきょうします。','で',['を','に','と'],'J’étudie à la bibliothèque.','で indique le lieu de cette action.'],
 ['p04','particle','g079','Complète la particule de citation.','あしたはあめだ＿おもいます。','と',['を','で','に'],'Je pense qu’il pleuvra demain.','と introduit le contenu de la pensée avant おもいます.'],
 ['v01','vocabulary','g023','Complète : « Je bois de l’eau ».','＿をのみます。','みず',['ほん','くつ','つくえ'],'Je bois de l’eau.','みず signifie « eau ». La traduction précise le mot attendu.'],
 ['v02','vocabulary','g023','Complète : « Je lis un livre ».','＿をよみます。','ほん',['パン','みず','いす'],'Je lis un livre.','ほん signifie « livre » et よみます signifie « lire ».'],
 ['v03','vocabulary','g020','Complète : « Je vais à l’école en train ».','＿でがっこうへいきます。','でんしゃ',['じしょ','えんぴつ','とけい'],'Je vais à l’école en train.','でんしゃ signifie « train ». で indique le moyen de transport.'],
 ['v04','vocabulary','g163','Complète : « Ce stylo est facile à utiliser ».','この＿はつかいやすいです。','ペン',['ねこ','あめ','やすみ'],'Ce stylo est facile à utiliser.','ペン signifie « stylo ». つかいやすい signifie « facile à utiliser ».'],
 ['c01','conjugation','g018','Choisis le passé affirmatif poli.','たべます → ?','たべました',['たべません','たべませんでした','たべます'],'J’ai mangé.','Au passé affirmatif poli, ます devient ました.'],
 ['c02','conjugation','g059','Choisis la forme en て de たべます.','たべます → ?','たべて',['たべって','たべんで','たべた'],'manger → forme en て','たべる est un verbe du groupe 2 : る devient て.'],
 ['c03','conjugation','g059','Choisis la forme en て de のみます.','のみます → ?','のんで',['のみて','のって','のんだ'],'boire → forme en て','Pour のむ, la terminaison む devient んで.'],
 ['c04','conjugation','g100','Choisis la forme potentielle polie : « pouvoir parler ».','はなします → ?','はなせます',['はなします','はなしました','はなしません'],'Je peux parler.','はなす devient はなせる au potentiel, puis はなせます à la forme polie.'],
 ['o01','order','g001','Assemble « Je suis étudiant ».','Commence par わたしは.','わたしはがくせいです。',['です。','わたしは','がくせい'],'Je suis étudiant.','Le thème わたしは précède がくせいです.'],
 ['o02','order','g023','Assemble « Je bois de l’eau ».','Commence par わたしは.','わたしはみずをのみます。',['のみます。','みずを','わたしは'],'Je bois de l’eau.','Place le thème, puis le complément en を, puis le verbe.'],
 ['o03','order','g005','Assemble « Ceci est mon livre ».','Commence par これは.','これはわたしのほんです。',['ほんです。','これは','わたしの'],'Ceci est mon livre.','わたしの précise à qui appartient le livre.'],
 ['o04','order','g106','Assemble « J’étudie en écoutant de la musique ».','Place l’action en ながら avant l’action principale.','おんがくをききながらべんきょうします。',['べんきょうします。','ききながら','おんがくを'],'J’étudie en écoutant de la musique.','おんがくをききながら décrit l’action simultanée.'],
 ['g01','grammar','g060','Exprime une permission.','ここでしゃしんを＿。','とってもいいです',['とってはいけません','とりませんでした','とりたくないです'],'On peut prendre des photos ici.','La forme en て + もいいです exprime une permission.'],
 ['g02','grammar','g061','Exprime une interdiction.','ここでたばこを＿。','すってはいけません',['すってもいいです','すいたいです','すっています'],'Il est interdit de fumer ici.','La forme en て + はいけません exprime une interdiction.'],
 ['g03','grammar','g106','Exprime deux actions simultanées : étudier en écoutant.','おんがくを＿、べんきょうします。','ききながら',['きいたあとで','きくまえに','きかないで'],'J’étudie en écoutant de la musique.','ながら relie deux actions simultanées faites par la même personne.'],
 ['g04','grammar','g168','Exprime une action qui vient de se terminer.','さっきごはんを＿。','たべたばかりです',['たべるところです','たべたいです','たべません'],'Je viens de manger.','た + ばかりです exprime une action récente du point de vue du locuteur.'],
 ['d01','dialogue','g003','Réponds oui à la question.','A：がくせいですか。\nB：＿','はい、がくせいです。',['いいえ、がくせいじゃありません。','おやすみなさい。','いただきます。'],'Êtes-vous étudiant ? — Oui, je suis étudiant.','はい confirme la question posée.'],
 ['d02','dialogue','g011','Indique que les toilettes sont là-bas.','A：トイレはどこですか。\nB：＿','あそこです。',['さんじです。','せんえんです。','げつようびです。'],'Où sont les toilettes ? — Là-bas.','どこ demande un lieu ; あそこ désigne un endroit éloigné.'],
 ['d03','dialogue','g025','Accepte l’invitation.','A：いっしょにえいがをみませんか。\nB：＿','ええ、みましょう。',['すみません、きょうはちょっと…。','いいえ、みません。','えいがはみたくないです。'],'Voulez-vous voir un film ensemble ? — Oui, allons le voir.','ましょう permet de reprendre positivement la proposition.'],
 ['d04','dialogue','g098','Accepte poliment de regarder la lettre.','A：このてがみをみていただけませんか。\nB：＿','ええ、いいですよ。',['すみません、いまはできません。','いいえ、みません。','おやすみなさい。'],'Pourriez-vous regarder cette lettre ? — Oui, bien sûr.','いいですよ accepte la demande ; les deux premières alternatives la refusent.'],
 ['r01','reading','g017','À quelle heure cette personne se lève-t-elle ?','まいあさろくじにおきます。しちじにあさごはんをたべます。','ろくじ',['しちじ','はちじ','くじ'],'Chaque matin, je me lève à six heures. Je prends mon petit-déjeuner à sept heures.','ろくじ se rapporte à おきます ; しちじ se rapporte au petit-déjeuner.'],
 ['r02','reading','g020','Quel moyen de transport utilise cette personne ?','がっこうへでんしゃでいきます。えきからがっこうまであるきます。','でんしゃ',['バス','タクシー','じてんしゃ'],'Je vais à l’école en train. Je marche de la gare à l’école.','Le trajet en train est indiqué par でんしゃで.'],
 ['r03','reading','g018','Qu’a fait cette personne hier ?','きのうはほんをよみました。テレビはみませんでした。','ほんをよみました。',['テレビをみました。','ほんをかいました。','えいがをみました。'],'Hier, j’ai lu un livre. Je n’ai pas regardé la télévision.','よみました est affirmatif ; みませんでした est négatif.'],
 ['r04','reading','g100','Que sait faire cette personne maintenant ?','まえはにほんごがはなせませんでした。いまはすこしはなせます。','にほんごがすこしはなせます。',['にほんごがはなせません。','にほんごがぜんぶわかります。','にほんごでほんがかけます。'],'Avant, je ne pouvais pas parler japonais. Maintenant, je peux le parler un peu.','いま introduit la capacité actuelle. Le texte ne parle ni d’écriture ni de compréhension totale.'],
 ['e01','correction','g023','Remplace が pour dire « Je bois de l’eau ».','みずがのみます。','を',['に','で','と'],'みずをのみます。 — Je bois de l’eau.','Le complément direct de のみます est marqué par を.'],
 ['e02','correction','g024','Remplace に pour dire « J’étudie à la bibliothèque ».','としょかんにべんきょうします。','で',['を','と','の'],'としょかんでべんきょうします。 — J’étudie à la bibliothèque.','Le lieu de l’action べんきょうします est marqué par で.'],
 ['e03','correction','g018','Corrige uniquement le verbe pour exprimer un fait passé.','きのう、えいがをみます。','みました',['みます','みましょう','みたいです'],'Hier, j’ai regardé un film.','きのう situe le fait hier : il faut ici le passé みました.'],
 ['e04','correction','g106','Corrige きくながら.','おんがくをきくながらべんきょうします。','ききながら',['きいてながら','きいたながら','きかないながら'],'J’étudie en écoutant de la musique.','ながら suit la base de la forme en ます : ききます → ききながら.'],
 ['t01','transform','g018','Mets le verbe au négatif poli, sans changer le reste.','パンをたべます。','パンをたべません。',['パンをたべました。','パンをたべます。','パンをたべましょう。'],'Je ne mange pas de pain.','ます devient ません au négatif non passé poli.'],
 ['t02','transform','g018','Mets le verbe au passé affirmatif poli.','がっこうへいきます。','がっこうへいきました。',['がっこうへいきません。','がっこうへいきます。','がっこうへいきませんでした。'],'Je suis allé à l’école.','ました exprime le passé affirmatif poli.'],
 ['t03','transform','g050','Mets l’adjectif au passé affirmatif poli.','このほんはおもしろいです。','このほんはおもしろかったです。',['このほんはおもしろいでした。','このほんはおもしろくないです。','このほんはおもしろいです。'],'Ce livre était intéressant.','Pour un adjectif en い, retire い et ajoute かったです.'],
 ['t04','transform','g100','Exprime la capacité : « Je peux parler japonais ».','にほんごをはなします。','にほんごがはなせます。',['にほんごをはなしました。','にほんごをはなしません。','にほんごをはなしたいです。'],'Je peux parler japonais.','はなせます est la forme potentielle. が peut marquer ce que l’on sait parler.'],
];
export const BANK = rows.map(([id,type,grammarId,instruction,prompt,answer,options,translation,explanation]) => ({id,type,grammarId,instruction,prompt,answer,options,translation,explanation}));
